### ISSUE TITLE
Disable TabLayout On Click

### ISSUE THREAD

**Issue by morteza-moradi** [Andy671/Dachshund-Tab-Layout#3]
I'm using the new class provided by the design library : TabLayout. And I want in specific cases that the one I'm using can't change tab anymore.
I manage to disable swipe on its viewpager but I can't figure out how to disable the change of page by clicking on tabs.
Thank's in advance.

**In The Normal Tablayout with below code i can disable it ** 

` LinearLayout tabStrip = ((LinearLayout)mTabLayout.getChildAt(0));
    for(int i = 0; i < tabStrip.getChildCount(); i++) {
        tabStrip.getChildAt(i).setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                return true;
            }
        });
    }
`

**But in This Library How Can I Do It ?**

**Comment by Andy671** [comment]
I just tried your code, and this works just Perfectly! 

So your approach is right in this situation.
