### ISSUE TITLE
How to Use setEdgeRadius(int edgeRadius) to change Radius LineMoveIndicator?

### ISSUE THREAD

**Issue by saeed74** [Andy671/Dachshund-Tab-Layout#4]
Hi, I didnt found help about to set edge radius of LineMoveIndicator to ZERO!
i want it as a keen rectangle!
where to use  setEdgeRadius(int edgeRadius) ?

**Comment by Andy671** [comment]
It is as easy as in LineFadeIndicator. 
We have setEdgeRadius method right here!
```
LineMoveIndicator lineMoveIndicator = new LineMoveIndicator(tabLayout);
lineMoveIndicator.setEdgeRadius(0);
tabLayout.setAnimatedIndicator(lineMoveIndicator);
```
