### ISSUE TITLE
Not possible to set a custom animated indicator or select default ones programatically.

### ISSUE THREAD

**Issue by Krad23** [Andy671/Dachshund-Tab-Layout#8]
To reproduce:
1. Import dachsund to a new empty project
2. Add a DachsundTabLayout to the bottom of the main activity view with the following xml
    <com.kekstudio.dachshundtablayout.DachshundTabLayout
        android:id="@+id/homeTabLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBotomOf="parent"
        />
3. In the MainActivity's onStart, onCreate or onResume call **setAnimatedIndicator(new LineMoveIndicator(dachsundTabLayout))**
4. Run the app

Expected:
App uses LineMoveIndicator once it runs

Actual:
App uses the default DachshundIndicator

Problem, the way I understand it:
setupAnimatedIndicator should not overule an AnimatedIndicator set through setAnimatedIndicator.

When **animatedIndicator** is set programatically by calling **setAnimatedIndicator** in the Android Activity's **onCreate, onStart or onResume** methods the setupAnimatedIndicator is still called afterwards and the programatically set indicator with either default or whatever was set through xml.

A potential quick fix could be to add a CUSTOM flag for the animatedIndicatorType that could be both set from xml and would be automatically used once setAnimatedIndicator has been called.

**Comment by Krad23** [comment]
Even easier way to reproduce it is to just add this line to the sample project in this repo.

In SampleActivity, as a last call in onCreate add this line
    tabLayout.setAnimatedIndicator(new LineMoveIndicator(tabLayout));

**Comment by Cuiernao** [comment]
我也遇到一样的问题了，为啥设置下面的动画，没有效果！
tabLayout.setAnimatedIndicator(new LineMoveIndicator(tabLayout));

**Comment by Andy671** [comment]
Have you found the solution of the problem?

**Comment by Andy671** [comment]
@Krad23 , I've fixed this issue in v0.3.3.
